name: main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev zlib1g-dev

    - name: Build
      run: swift build -v

    - name: Run Tests
      run: swift test -v
